In [1]:
print(__doc__)

# Code source adapted from: Jaques Grobler
# License: BSD 3 clause

import random
import matplotlib.pyplot as plt
import numpy as np
import pandas
import os
import csv
import pprint
import time
import NeuralNetworkModel as NNM
import LogisticRegressionModel as LRM
import SoftmaxRegressionModel as SRM
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

pp = pprint.PrettyPrinter(indent=4)

Automatically created module for IPython interactive environment


In [2]:
# Read and treat training dataset
dataset_train = pandas.read_csv('fashion-mnist-dataset/fashion-mnist_train.csv').values #np.genfromtxt('fashion-mnist-dataset/fashion-mnist_train.csv', delimiter=',')
y_true = dataset_train[:,0]
dataset_train = np.delete(dataset_train, 0, 1).T
dataset_train = dataset_train / dataset_train.max()

# Read and treat test dataset
dataset_test = pandas.read_csv('fashion-mnist-dataset/fashion-mnist_test.csv').values
target_test = dataset_test[:,0]
dataset_test = np.delete(dataset_test, 0, 1).T
dataset_test = dataset_test / dataset_test.max()

# Separate train dataset in Train and Validation Data
half = len(y_true)//2

data_train = dataset_train[:,:half]
target_train = y_true[:half]
data_val = dataset_train[:,half:]
target_val = y_true[half:]

In [3]:
#######################################
#######                         #######
#######   Logistic Regression   #######
#######                         #######  
#######################################

logistic_model = LRM.Model(data_train, target_train, epochs=10, alpha=0.01, batch_size=1)
logistic_model.Fit()
logistic_y_pred = logistic_model.Predict(data_val, target_val)


Training class 1 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 2 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 3 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 4 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 5 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 6 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 7 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 8 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 9 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 10 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10


In [4]:
print(confusion_matrix(target_val, logistic_y_pred))
print(classification_report(target_val, logistic_y_pred))

[[2512   13   35  132   48    2  183    2   36    0]
 [  16 2869   15   75   11    0    9    0    2    1]
 [ 111    4 1827   35  855    1  148    0   27    0]
 [ 124   27    8 2572  168    0   70    0   17    1]
 [  19    3  109  102 2759    0   97    0   11    0]
 [   4    3    3    6    3 2588    2  207   59  143]
 [ 590   11  224   98  716    1 1252    3   66    1]
 [   0    0    1    0    0   59    0 2772    8  104]
 [  28    1   11   38   42   16   31   17 2822    1]
 [   0    0    0    0    0   32    0  122    6 2853]]
             precision    recall  f1-score   support

          0       0.74      0.85      0.79      2963
          1       0.98      0.96      0.97      2998
          2       0.82      0.61      0.70      3008
          3       0.84      0.86      0.85      2987
          4       0.60      0.89      0.72      3100
          5       0.96      0.86      0.91      3018
          6       0.70      0.42      0.53      2962
          7       0.89      0.94      0.91  