In [2]:
print(__doc__)

# Code source adapted from: Jaques Grobler
# License: BSD 3 clause

import random
import matplotlib.pyplot as plt
import numpy as np
import pandas
import os
import csv
import pprint
import time
import NeuralNetworkModel as NNM
import LogisticRegressionModel as LRM
import SoftmaxRegressionModel as SRM
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

pp = pprint.PrettyPrinter(indent=4)

Automatically created module for IPython interactive environment


In [3]:
# Read and treat training dataset
dataset_train = pandas.read_csv('fashion-mnist-dataset/fashion-mnist_train.csv').values #np.genfromtxt('fashion-mnist-dataset/fashion-mnist_train.csv', delimiter=',')
y_true = dataset_train[:,0]
dataset_train = np.delete(dataset_train, 0, 1).T
dataset_train = dataset_train / dataset_train.max()

# Read and treat test dataset
dataset_test = pandas.read_csv('fashion-mnist-dataset/fashion-mnist_test.csv').values
target_test = dataset_test[:,0]
dataset_test = np.delete(dataset_test, 0, 1).T
dataset_test = dataset_test / dataset_test.max()

# Separate train dataset in Train and Validation Data
half = len(y_true)//2

data_train = dataset_train[:,:half]
target_train = y_true[:half]
data_val = dataset_train[:,half:]
target_val = y_true[half:]

In [3]:
#######################################
#######                         #######
#######   Logistic Regression   #######
#######                         #######  
#######################################

logistic_model = LRM.Model(data_train, target_train, epochs=10, alpha=0.01, batch_size=1)
logistic_model.Fit()
logistic_y_pred = logistic_model.Predict(data_val, target_val)


Training class 1 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 2 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 3 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 4 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 5 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 6 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 7 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 8 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 9 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10



Training class 10 of 10

Epochs: 1 / 10


Epochs: 2 / 10


Epochs: 3 / 10


Epochs: 4 / 10


Epochs: 5 / 10


Epochs: 6 / 10


Epochs: 7 / 10


Epochs: 8 / 10


Epochs: 9 / 10


Epochs: 10 / 10


In [4]:
print(confusion_matrix(target_val, logistic_y_pred))
print(classification_report(target_val, logistic_y_pred))

[[2512   13   35  132   48    2  183    2   36    0]
 [  16 2869   15   75   11    0    9    0    2    1]
 [ 111    4 1827   35  855    1  148    0   27    0]
 [ 124   27    8 2572  168    0   70    0   17    1]
 [  19    3  109  102 2759    0   97    0   11    0]
 [   4    3    3    6    3 2588    2  207   59  143]
 [ 590   11  224   98  716    1 1252    3   66    1]
 [   0    0    1    0    0   59    0 2772    8  104]
 [  28    1   11   38   42   16   31   17 2822    1]
 [   0    0    0    0    0   32    0  122    6 2853]]
             precision    recall  f1-score   support

          0       0.74      0.85      0.79      2963
          1       0.98      0.96      0.97      2998
          2       0.82      0.61      0.70      3008
          3       0.84      0.86      0.85      2987
          4       0.60      0.89      0.72      3100
          5       0.96      0.86      0.91      3018
          6       0.70      0.42      0.53      2962
          7       0.89      0.94      0.91  

In [4]:
#######################################
#######                         #######
#######   Softmax Regression    #######
#######                         #######  
#######################################

softmax_model = SRM.Model(data_train, target_train, epochs=10, alpha=0.001, batch_size=1)
softmax_model.Fit()
softmax_y_pred = softmax_model.Predict(data_val, target_val)

Epochs: 10 / 10: 100%|██████████| 30000/30000 [00:05<00:00, 5881.37it/s]


In [5]:
print(confusion_matrix(target_val, softmax_y_pred))
print(classification_report(target_val, softmax_y_pred))

[[1020   53  300  986  218    6  224   58   53   45]
 [  59 1423   38  339  523    9  259  223  116    9]
 [ 254   97 1235   47  496   53  519    6  170  131]
 [ 487  707  163  972  255    4  314    8   75    2]
 [ 238  312  449  137 1069   62  492    6  197  138]
 [ 106  127  212   77   64  504  328  517  599  484]
 [ 741   70  541  255  558   46  534   20  122   75]
 [   8   53   50   13    5   64   17 2109  291  334]
 [  97   73  398   77  253   79  217   72 1406  335]
 [  12   93   45    0   26  494  173  188  406 1576]]
             precision    recall  f1-score   support

          0       0.34      0.34      0.34      2963
          1       0.47      0.47      0.47      2998
          2       0.36      0.41      0.38      3008
          3       0.33      0.33      0.33      2987
          4       0.31      0.34      0.33      3100
          5       0.38      0.17      0.23      3018
          6       0.17      0.18      0.18      2962
          7       0.66      0.72      0.69  

In [6]:
#######################################
#######                         #######
#######     Neural Network      #######
#######                         #######  
#######################################

neural_model = NNM.Model(data_train, target_train, activation="ReLU", epochs=1, alpha=0.01, l_hidden=1, hidden_neurons=512, batch_size=1, use_softmax=True)
for i in range(10):
    neural_model.fit()

    neural_y_pred = neural_model.Predict(data_val, target_val)
    print(confusion_matrix(target_val, neural_y_pred))
    print(classification_report(target_val, neural_y_pred))
    neural_model.alpha /= 2

Epochs: 1 / 1:   0%|          | 0/30000 [00:00<?, ?it/s]/home/matheusmortatti/git/Machine-Learning-Class/Assignment02/NeuralNetworkModel.py:186: ComplexWarning: Casting complex values to real discards the imaginary part
  self.D[k][i,:] = (a*err[i])[:,0]
/home/matheusmortatti/git/Machine-Learning-Class/Assignment02/NeuralNetworkModel.py:187: ComplexWarning: Casting complex values to real discards the imaginary part
  self.bD[k][i] = err[i]
Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:14:06<00:00,  6.90it/s]


[[1606   15   32  164   13    5 1086    0   42    0]
 [   8 2858   22   78    7    0   21    0    4    0]
 [  37    4 1856   20  527    4  548    1   11    0]
 [  79   64   20 2328  194    3  278    0   21    0]
 [  10   12  236   95 2354    1  381    0   11    0]
 [   5    0    1    4    2 2765   10  120   26   85]
 [ 301    5  228   76  343    1 1972    1   34    1]
 [   1    0    1    1    0  161    1 2568    7  204]
 [  48    4   59   11   23   28  158   17 2658    1]
 [   1    0    0    0    1   53    1   78    2 2877]]
             precision    recall  f1-score   support

          0       0.77      0.54      0.63      2963
          1       0.96      0.95      0.96      2998
          2       0.76      0.62      0.68      3008
          3       0.84      0.78      0.81      2987
          4       0.68      0.76      0.72      3100
          5       0.92      0.92      0.92      3018
          6       0.44      0.67      0.53      2962
          7       0.92      0.87      0.90  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:27<00:00,  6.86it/s]


[[2500   16   89  135   11    7  159    0   46    0]
 [  19 2860   15   82    8    0    8    0    6    0]
 [  50    5 2354   22  387    4  164    0   22    0]
 [ 173   32   37 2434  196    1   87    0   27    0]
 [  15    9  344   80 2331    1  300    0   20    0]
 [   2    1    1    4    2 2826    4  101   17   60]
 [ 703    7  481   78  282    3 1348    0   59    1]
 [   0    0    0    1    0  171    1 2604   11  156]
 [  35    3   54   11   20   23   56   12 2791    2]
 [   1    0    1    0    0   55    0  106    2 2848]]
             precision    recall  f1-score   support

          0       0.71      0.84      0.77      2963
          1       0.98      0.95      0.96      2998
          2       0.70      0.78      0.74      3008
          3       0.85      0.81      0.83      2987
          4       0.72      0.75      0.74      3100
          5       0.91      0.94      0.93      3018
          6       0.63      0.46      0.53      2962
          7       0.92      0.88      0.90  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:25<00:00,  6.84it/s]


[[2313   20   54  198   16    5  308    0   49    0]
 [   9 2895   10   69    4    0    7    0    4    0]
 [  47    9 2260   42  390    2  241    0   17    0]
 [  87   45   26 2601  116    1   86    0   25    0]
 [  10   13  291  149 2361    0  256    0   20    0]
 [   2    1    1    5    2 2789    3  117   26   72]
 [ 504   13  319  121  306    2 1652    1   43    1]
 [   0    0    0    1    0  138    0 2667   10  128]
 [  30    5   37   14   24   18   85   13 2779    2]
 [   1    0    0    1    1   35    0  117    2 2856]]
             precision    recall  f1-score   support

          0       0.77      0.78      0.78      2963
          1       0.96      0.97      0.97      2998
          2       0.75      0.75      0.75      3008
          3       0.81      0.87      0.84      2987
          4       0.73      0.76      0.75      3100
          5       0.93      0.92      0.93      3018
          6       0.63      0.56      0.59      2962
          7       0.91      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:46<00:00,  6.82it/s]


[[2330   24   53  170   15    5  312    0   54    0]
 [  10 2911    9   52    4    0    9    0    3    0]
 [  47    7 2210   46  415    3  261    0   19    0]
 [  98   71   30 2567  118    1   77    0   25    0]
 [  10   16  250  144 2406    0  253    0   21    0]
 [   4    0    1    3    2 2832    3  102   24   47]
 [ 505   12  278  116  311    1 1688    0   49    2]
 [   0    0    0    1    0  160    0 2678    9   96]
 [  25    5   30   13   18   20   73   11 2811    1]
 [   1    0    0    1    1   55    0  142    2 2811]]
             precision    recall  f1-score   support

          0       0.77      0.79      0.78      2963
          1       0.96      0.97      0.96      2998
          2       0.77      0.73      0.75      3008
          3       0.82      0.86      0.84      2987
          4       0.73      0.78      0.75      3100
          5       0.92      0.94      0.93      3018
          6       0.63      0.57      0.60      2962
          7       0.91      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:08<00:00,  6.84it/s]


[[2202   18   50  149   14    5  472    0   53    0]
 [  13 2888   10   72    2    0   10    0    3    0]
 [  46    6 2239   35  374    3  284    0   21    0]
 [ 102   40   26 2550  139    1  104    0   25    0]
 [  10    6  289  105 2401    0  269    0   20    0]
 [   5    1    1    5    2 2804    3  111   28   58]
 [ 397    6  285   91  290    0 1842    1   49    1]
 [   0    0    0    1    0  134    0 2672    8  129]
 [  23    4   34   12   20   17   68   13 2815    1]
 [   1    0    0    1    1   43    0  106    2 2859]]
             precision    recall  f1-score   support

          0       0.79      0.74      0.76      2963
          1       0.97      0.96      0.97      2998
          2       0.76      0.74      0.75      3008
          3       0.84      0.85      0.85      2987
          4       0.74      0.77      0.76      3100
          5       0.93      0.93      0.93      3018
          6       0.60      0.62      0.61      2962
          7       0.92      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:30<00:00,  6.87it/s]


[[2319   18   52  120   11    5  383    0   55    0]
 [  16 2892   12   64    2    0    8    0    4    0]
 [  50    6 2314   34  300    3  277    0   24    0]
 [ 135   43   28 2512  141    1  100    0   27    0]
 [  13    7  377   98 2291    0  292    0   22    0]
 [   4    1    1    5    2 2804    3  120   27   51]
 [ 458    6  310   88  249    0 1801    1   48    1]
 [   0    0    0    1    0  123    0 2707    9  104]
 [  21    3   32   11   19   17   73   13 2817    1]
 [   1    0    0    1    1   48    0  140    2 2820]]
             precision    recall  f1-score   support

          0       0.77      0.78      0.78      2963
          1       0.97      0.96      0.97      2998
          2       0.74      0.77      0.75      3008
          3       0.86      0.84      0.85      2987
          4       0.76      0.74      0.75      3100
          5       0.93      0.93      0.93      3018
          6       0.61      0.61      0.61      2962
          7       0.91      0.92      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:05<00:00,  6.83it/s]


[[2341   19   57  132   15    5  342    0   52    0]
 [  15 2895   12   64    2    0    7    0    3    0]
 [  53    7 2320   36  347    3  221    0   21    0]
 [ 131   43   28 2539  129    1   90    0   26    0]
 [  12    6  322  113 2376    0  246    0   25    0]
 [   5    1    1    5    2 2807    3  115   27   52]
 [ 466    6  340   92  278    0 1733    1   45    1]
 [   0    0    0    1    0  130    0 2690   10  113]
 [  21    3   40   13   22   18   62   12 2815    1]
 [   1    0    0    1    1   46    0  131    2 2831]]
             precision    recall  f1-score   support

          0       0.77      0.79      0.78      2963
          1       0.97      0.97      0.97      2998
          2       0.74      0.77      0.76      3008
          3       0.85      0.85      0.85      2987
          4       0.75      0.77      0.76      3100
          5       0.93      0.93      0.93      3018
          6       0.64      0.59      0.61      2962
          7       0.91      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:24<00:00,  6.90it/s]


[[2387   20   53  126   13    5  308    0   51    0]
 [  15 2897   12   62    2    0    8    0    2    0]
 [  57    7 2281   37  355    3  245    0   23    0]
 [ 146   43   26 2528  129    1   88    0   26    0]
 [  14    6  297  113 2386    0  262    0   22    0]
 [   6    0    1    5    2 2806    3  116   27   52]
 [ 486    6  309   90  277    0 1748    1   44    1]
 [   0    0    0    1    0  125    0 2691   10  117]
 [  25    3   33   14   19   19   66   12 2815    1]
 [   1    0    0    2    1   42    0  123    2 2842]]
             precision    recall  f1-score   support

          0       0.76      0.81      0.78      2963
          1       0.97      0.97      0.97      2998
          2       0.76      0.76      0.76      3008
          3       0.85      0.85      0.85      2987
          4       0.75      0.77      0.76      3100
          5       0.94      0.93      0.93      3018
          6       0.64      0.59      0.61      2962
          7       0.91      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:17<00:00,  6.88it/s]


[[2355   20   52  126   13    5  341    0   51    0]
 [  15 2897   11   62    2    0    8    0    3    0]
 [  57    7 2267   35  369    3  249    0   21    0]
 [ 136   44   26 2534  131    1   90    0   25    0]
 [  13    7  291  113 2396    0  258    0   22    0]
 [   6    0    1    5    2 2807    3  115   27   52]
 [ 472    7  294   90  284    0 1769    1   44    1]
 [   0    0    0    1    0  126    0 2688   12  117]
 [  23    3   32   14   19   19   72   12 2812    1]
 [   1    0    0    2    1   42    0  123    2 2842]]
             precision    recall  f1-score   support

          0       0.77      0.79      0.78      2963
          1       0.97      0.97      0.97      2998
          2       0.76      0.75      0.76      3008
          3       0.85      0.85      0.85      2987
          4       0.74      0.77      0.76      3100
          5       0.93      0.93      0.93      3018
          6       0.63      0.60      0.62      2962
          7       0.91      0.91      0.91  

Epochs: 1 / 1: 100%|██████████| 30000/30000 [1:13:19<00:00,  6.84it/s]


[[2354   21   52  127   13    5  340    0   51    0]
 [  15 2897   12   62    2    0    8    0    2    0]
 [  57    7 2285   34  351    3  250    0   21    0]
 [ 136   46   26 2533  129    1   91    0   25    0]
 [  12    7  315  115 2365    0  264    0   22    0]
 [   6    0    1    5    2 2807    3  115   27   52]
 [ 475    7  309   91  276    0 1758    1   44    1]
 [   0    0    0    1    0  126    0 2689   12  116]
 [  22    3   32   14   20   19   72   12 2812    1]
 [   1    0    0    2    1   42    0  123    2 2842]]
             precision    recall  f1-score   support

          0       0.76      0.79      0.78      2963
          1       0.97      0.97      0.97      2998
          2       0.75      0.76      0.76      3008
          3       0.85      0.85      0.85      2987
          4       0.75      0.76      0.76      3100
          5       0.93      0.93      0.93      3018
          6       0.63      0.59      0.61      2962
          7       0.91      0.91      0.91  

In [ ]:
print(confusion_matrix(target_val, neural_y_pred))
print(classification_report(target_val, neural_y_pred))